# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Dmitry Avershin
tagline:          'My awesome blog'
description:      'Passionate software engineer, interested in functional programming, distributed systems and building cool things.'
url:              http://dmitraver.github.io

# tracking
google_analytics: UA-128610108-1

author:
  name:           'Dmitry Avershin'
  url:            https://github.com/dmitraver

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
